name: KoolChatFilter
main: eu.koolfreedom.KoolChatFilter
loader: eu.koolfreedom.KoolLibraryManager
version: '1.0'
description: My best attempt at a chat filter plugin
author: gamingto12
api-version: 1.21.10

permissions:
  kfc.default:
    children:
      - kfc.command.koolchatfilter
      - kfc.command.permbans
  kfc.admin:
    children:
      - kfc.command.crash
      - kfc.command.obliterate
      - kfc.command.reload