name: KoolChatFilter
main: eu.koolfreedom.KoolChatFilter
version: ${project.version}
description: My best attempt at a chat filter plugin
author: gamingto12
api-version: 1.21

permissions:
  kf.default:
    children:
      - kfc.command.koolchatfilter
  kf.admin:
    children:
      - kfc.command.crash
      - kfc.command.obliterate
      - kfc.command.permbans
      - kfc.command.reload