name: KoolChatFilter
main: eu.koolfreedom.KoolChatFilter
version: ${project.version}
description: Hackjob of a chat filter
author: gamingto12
api-version: 1.21.1

permissions:
  kf.default:
    children:
      - kfc.command.koolchatfilter
  kf.admin:
    children:
      - kfc.command.crash
      - kfc.command.obliterate
      - kfc.command.permbans
      - kfc.command.reload